### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Tanete** [Tanete/weibo_search#2]
- [x] Run script periodically to collect more data
- [x] Think about data mining
- [x] Try to visualize data
- [x] Try to intergrate to Rails
